name: MuteDeaths
main: net.evmodder.MuteDeaths.MuteDeaths
author: EvModder
website: https://github.com/EvModder/MuteDeaths
description: Mute deaths (and kills) from specific players
#.1=update for 1.20.4
version: 1.1
api-version: 1.13
soft-depend: [Dropheads]

commands:
  mutedeath:
    description: Mute death messages from a player
    usage: /mutedeaths <who>
    aliases: [mutedeaths]
    permission: mutedeaths.deaths
    permission-message: You do not have permission to do this.

  mutekill:
    description: Mute kill messages from a spammy murderer
    usage: /mutekills <who>
    aliases: [mutekills]
    permission: mutedeaths.kills
    permission-message: You do not have permission to do this.

  mutebehead:
    description: Mute behead messages
    usage: /mutebeheads LOCAL/GLOBAL, /mutebeheads by/of <who>
    aliases: [mutebeheads]
    permission: mutedeaths.beheads
    permission-message: You do not have permission to do this.


permissions:
  mutedeaths.deaths:
    description: Permission to use /mutedeaths
    default: true

  mutedeaths.kills:
    description: Permission to use /mutekills
    default: true

  mutedeaths.beheads:
    description: Permission to use /mutebeheads
    default: true